.\" Manpage for blugon
.\" author: Felix Springer <felixspringer149@gmail.com>
.\" github: https://github.com/jumper149/blugon
.TH man 8 "06 January 2019" "1.11.2" "blugon man page"
.SH NAME
blugon \- simple Blue Light Filter for X
.SH SYNOPSIS
.B blugon
.RB [\|\-h\|]
.RB [\|\-v\|]
.RB [\|\-V\|]
.RB [\|\-p\|]
.RB [\|\-o\|]
.RB [\|\-r\|]
.RB [\|\-S
.IR temperature \|]
.RB [\|\-s\|]
.RB [\|\-f\|]
.RB [\|\-i
.IR interval \|]
.RB [\|\-c
.IR directory \|]
.RB [\|\-b
.IR backend \|]
.RB [\|\-w\|]

.SH DESCRIPTION
blugon is a simple blue light filter that uses xgamma as a backed and is configured in "$XDG_CONFIG_HOME/blugon/" or "$HOME/.config/blugon/" as fallback.

Configuration files are 'config' and 'gamma'.

You can get a 'config' file with default values by using:

    $ blugon --printconfig > ~/.config/blugon/config

You can copy the default 'gamma' configuration into your home directory:

    $ cp /usr/share/blugon/configs/default/gamma ~/.config/blugon/

There are more templates for 'gamma' in "/usr/share/blugon/".
Syntax in 'gamma' has to be in one of the following two forms:

    $ [hour] [minute]   [red]   [green] [blue]  
    $ [hour] [minute]   [temperature]

[red], [green], [blue] between 0 and 1

[temperature] between 1000 (red) and 20000 (blue), default is 6600

You can enable the systemd service as user:

    $ systemctl --user enable blugon.service

In 'current' the color temperature for \-\-readcurrent is stored.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show quick help and then exit.

.TP
.B \-v, \-\-version
Display the version of your blugon and then exit.

.TP
.B \-V, \-\-verbose
Be verbose, print additional information to debug the program.

.TP
.B \-p, \-\-printconfig
Print the default configuration to stdout and then exit.

.TP
.B \-o, \-\-once
Apply the gamma values of the current time and then exit.

.TP
.B \-r, \-\-readcurrent
Read temperature value from file 'current' instead of 'gamma'.
Useful for being able to control current temperature with hotkeys or scripts in conjunction with \-\-setcurrent.

.TP
.B \-S\  temperature \fR,\ \fB\-\-setcurrent=temperature
Set temperature value to file 'current'.
Prepend + or - to the temperature to, instead of setting it absolutely, add or subtract the value.
Automatically implies the \-\-readcurrent and \-\-once flags.

.TP
.B \-s, \-\-simulation
Start a simulation of the chosen configuration to see how it changes over the day.
Changing the interval will not have an effect here.
The program exits after the simulation.

.TP
.B \-f, \-\-fade
Fade in the screen color on startup.
This does not work with the \-\-simulation flag.

.TP
.B \-i\  seconds \fR,\ \fB\-\-interval=seconds
Set the time period blugon waits to refresh the gamma values of your screen in seconds.

.TP
.B \-c\  path \fR,\ \fB\-\-configdir=path
Specify the path that blugon is goin to search for configuration files like 'config, 'gamma' and 'current'.
Path must lead to directory.

.TP
.B \-b\  backend \fR,\ \fB\-\-backend=backend
Specify the backend to be used.
Make sure the desired backend is installed on your system.

Available backends are:
    xgamma
    scg
    tty

.TP
.B \-w, \-\-waitforx
Instead of crashing when the backend fails the program will continue.
This is automatically used by the systemd service to prevent failing when switching to another TTY.

.SH EXAMPLES
To just apply the blue filter and then exit use:

    $ blugon --once

You can run blugon in your tty with appending the following code to your "~/.bashrc":

    $ if [ "$TERM" = "linux" ]; then
    $   blugon --once --backend="tty" && clear
    $   (blugon --backend="tty")&
    $ fi

.SH SEE ALSO
xgamma(8)
.SH PROBLEMS
If you have trouble enabling the systemd service, but starting it later on works fine, try increasing the time before restarting (blugon will restart if it cannot find the X-Server) in 'config' (example with 3 seconds):

    $ [wait_for_x]
    $ sleep_after_failed_startup = 3

.SH AUTHOR
Felix Springer <felixspringer149@gmail.com>
