.\" Manpage for blugon
.\" author: Felix Springer <felixspringer149@gmail.com>
.\" github: https://github.com/jumper149/blugon
.TH man 8 "06 January 2019" "1.0" "blugon man page"
.SH NAME
blugon \- blue light filter for X11
.SH SYNOPSIS
.B blugon
.RB [\|\-h\|]
.RB [\|\-v\|]
.RB [\|\-i
.IR interval \|]
.RB [\|\-c
.IR config-dir \|]
.RB [\|\-s\|]

.SH DESCRIPTION
blugon is a simple blue light filter that uses xgamma as a backed and is configured in "~/.config/blugon/".
You can copy the standard configuration into your home directory:

    $ cp /usr/share/blugon/configs/default/gamma ~/.config/blugon/

At the moment configuration only includes the 'gamma' file.

.SH OPTIONS
.TP
.B \-h, \-\-help
Show quick help.

.TP
.B \-v, \-\-version
Display the version of your blugon.

.TP
.B \-i\  seconds \fR,\ \fB\-\-interval= seconds
Set the time period blugon takes to refresh the gamma values of your screen in seconds.

.TP
.B \-c\  path \fR,\ \fB\-\-config= path
Specify the path that blugon is goin to search for configuration files like 'gamma'.
Path must lead to directory.

.TP
.B \-s, \-\-simulation
Start a simulation of the chosen configuration to see how it changes over the day.
Changing the interval will not have an effect here.

.SH SEE ALSO
xgamma(8)
.SH BUGS
No known bugs.
.SH AUTHOR
Felix Springer <felixspringer149@gmail.com>
