#!/usr/bin/sh

EscStart="\e]P"

echo -en "${EscStart}${1}"
echo -en "${EscStart}${2}"
echo -en "${EscStart}${3}"
echo -en "${EscStart}${4}"
echo -en "${EscStart}${5}"
echo -en "${EscStart}${6}"
echo -en "${EscStart}${7}"
echo -en "${EscStart}${8}"
echo -en "${EscStart}${9}"
echo -en "${EscStart}${10}"
echo -en "${EscStart}${11}"
echo -en "${EscStart}${12}"
echo -en "${EscStart}${13}"
echo -en "${EscStart}${14}"
echo -en "${EscStart}${15}"
echo -en "${EscStart}${16}"
